r"""ASS subtitle generation. Pure string building — no side effects, no I/O.

Rewritten from legacy subtitle_renderer.generate_ass_with_rounded_bg. Key
differences:
  * Input is the typed ``ClipPlan`` + ``StyleDef`` (one shape, one type).
  * All timing via infra.time_util (single source — fixes legacy dup).
  * The rounded-rect background is drawn with ASS vector drawing (\p1), reusing
    the legacy ``_ass_rounded_rect_drawing`` algorithm (it was correct).
  * Box width derived from text_measure.measure_text_width (which now honours
    bold — fixes legacy background-too-narrow-for-bold bug).
"""

from __future__ import annotations

from garden_core.infra.time_util import format_ass_time
from garden_core.stage_render.text_measure import measure_text_width
from garden_core.types import BgStyle, ClipPlan, Cue, StyleDef

__all__ = ["build_ass", "rounded_rect_drawing"]


def rounded_rect_drawing(w: int, h: int, r: int) -> str:
    """ASS vector path for a rounded rectangle of size w×h, corner radius r."""
    r = max(0, min(r, w // 2, h // 2))
    return (
        f"m {r} 0 "
        f"l {w - r} 0 "
        f"b {w} 0 {w} {r} {w} {r} "
        f"l {w} {h - r} "
        f"b {w} {h} {w - r} {h} {w - r} {h} "
        f"l {r} {h} "
        f"b 0 {h} 0 {h - r} 0 {h - r} "
        f"l 0 {r} "
        f"b 0 0 {r} 0 {r} 0"
    )


def _ass_color(ass_hex: str, alpha_override: int | None = None) -> str:
    """Convert '&HAABBGGRR' to an ASS style colour 'AABBGGRR' (no leading &)."""
    s = ass_hex.lstrip("&H").upper()
    if len(s) == 8:
        a, b, g, r = s[0:2], s[2:4], s[4:6], s[6:8]
    elif len(s) == 6:  # no alpha given → opaque
        a, b, g, r = "00", s[0:2], s[2:4], s[4:6]
    else:
        a, b, g, r = "00", "00", "00", "FF"
    if alpha_override is not None:
        a = f"{alpha_override:02X}"
    return f"&H{a}{b}{g}{r}"


def _build_header(
    style: StyleDef, video_width: int, video_height: int,
    content_height: int, content_bottom_offset: int,
) -> str:
    # Font + vertical margin scale to the CONTENT region height (== video_height
    # for a 16:9 canvas; the centred 16:9 band for a vertical canvas), then the
    # margin is shifted down by content_bottom_offset so subtitles sit at the
    # bottom of the content, not the bottom of the full (letterboxed) canvas.
    font_size = style.font_size_px(content_height)
    # outline_width / shadow_depth are ratios of font_size → scale to px.
    outline_px = style.outline_width * font_size
    shadow_px = style.shadow_depth * font_size
    margin_v = int(style.margins[2] * content_height) + content_bottom_offset
    margin_l = int(style.margins[0] * video_width)
    margin_r = int(style.margins[1] * video_width)
    primary = _ass_color(style.primary_color)
    outline = _ass_color(style.outline_color)
    shadow = _ass_color(style.shadow_color)
    border = outline_px  # text outline (applies whether or not a box is drawn)

    bold_flag = -1 if style.bold else 0
    return (
        "[Script Info]\n"
        "; generated by garden-core\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {video_width}\n"
        f"PlayResY: {video_height}\n"
        "ScaledBorderAndShadow: yes\n"
        "WrapStyle: 2\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,{style.font_family},{font_size:.0f},"
        f"{primary},{primary},{outline},{shadow},{bold_flag},0,0,0,"
        f"100,100,0,0,1,{border},{shadow_px},"
        f"{style.align},{margin_l},{margin_r},{margin_v},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )


def _dialogue_line(
    layer: int, start_s: float, end_s: float, text: str, style: StyleDef,
    video_width: int, video_height: int, clip_start_s: float = 0.0,
) -> str:
    """Build one Dialogue line. Times are clip-relative (start at 0)."""
    start = format_ass_time(start_s)
    end = format_ass_time(end_s)
    return f"Dialogue: {layer},{start},{end},Default,,0,0,0,,{text}\n"


def _bg_dialogue(
    cue: Cue, bg: BgStyle, style: StyleDef,
    video_width: int, video_height: int,
    content_height: int, content_bottom_offset: int,
) -> str | None:
    """A background-box Dialogue line (layer 0) sized to the cue's text."""
    # Mirror _build_header: size to the content region, anchor to its bottom.
    font_size = style.font_size_px(content_height)
    text_w = measure_text_width(cue.text, font_size, style.font_family, style.bold)
    # bg.padding & corner_radius are ratios of font_size → scale to px.
    pad = bg.padding * font_size
    box_w = int(text_w + pad * 2)
    box_h = int(font_size * 1.4 + pad * 2)
    r = int(bg.corner_radius * font_size)
    # center the box horizontally; ASS alignment 2 = bottom-center
    drawing = rounded_rect_drawing(box_w, box_h, r)
    pos_x = video_width // 2 - box_w // 2
    margin_v = int(style.margins[2] * content_height) + content_bottom_offset
    pos_y = video_height - margin_v - box_h
    color = _ass_color(style.outline_color, alpha_override=bg.alpha)
    # \pos sets the drawing origin; \1c fills the rectangle
    text = (
        f"{{\\pos({pos_x},{pos_y})\\p1\\1c&H{color}&\\ bord0\\shad0}}"
        f"{drawing}{{\\p0}}"
    )
    return _dialogue_line(0, cue.start_s, cue.end_s, text, style,
                          video_width, video_height)


def _text_dialogue(
    cue: Cue, style: StyleDef,
    video_width: int, video_height: int,
) -> str:
    """The actual text Dialogue line (layer 1, on top of any background)."""
    display = cue.text
    if style.background is not None:
        # text sits in the box; keep clean
        display = cue.text.replace("\n", " ")
    return _dialogue_line(1, cue.start_s, cue.end_s, display, style,
                          video_width, video_height)


def build_ass(
    clip: ClipPlan, style: StyleDef, video_height: int, video_width: int | None = None,
) -> str:
    """Build the full ASS document for a clip. Pure function (string only).

    ``video_width`` defaults to 16:9 of the height (horizontal). Pass an
    explicit width for non-16:9 canvases (e.g. 1080 for a 1080×1920 vertical).
    """
    if video_width is None:
        video_width = int(video_height * 16 / 9)

    # Vertical canvas: the 16:9 horizontal content is scaled to the canvas width
    # and overlaid centred (see ffmpeg_render.render_vertical), so it occupies
    # only a band in the middle — not the full canvas height. Author subtitles in
    # that band's coordinate system: size font + margins to the band height, then
    # offset the margin down to the band's bottom edge. For a 16:9 canvas the
    # band IS the whole canvas (content_height == video_height, offset == 0), so
    # the horizontal path is byte-for-byte unchanged.
    content_height = video_height
    content_bottom_offset = 0
    band_h = round(video_width * 9 / 16)
    band_h += band_h % 2  # match ffmpeg scale=w:-2 even-height rounding
    if band_h < video_height:
        content_height = band_h
        content_bottom = (video_height + band_h) // 2
        content_bottom_offset = video_height - content_bottom

    out = _build_header(
        style, video_width, video_height, content_height, content_bottom_offset,
    )
    for cue in clip.cues:
        if not cue.text.strip():
            continue
        if style.background is not None:
            bg_line = _bg_dialogue(
                cue, style.background, style, video_width, video_height,
                content_height, content_bottom_offset,
            )
            if bg_line:
                out += bg_line
        out += _text_dialogue(cue, style, video_width, video_height)
    return out
